name: EfficientSurvival
version: @version@
main: tech.wakame.efficient_survival.EfficientSurvival
api-version: '1.16'
author: wakame_tech
commands:
  nl:
    description: manage named location
    usage: /<command> <subcommand> <params...>
  caveanalysis:
    description: analysis cave
    usage: /<command>
  vc:
    description: virtual chest
    usage: /<command> <subcommand> <params...>
  expconvert:
    description: player exp to exp bottle